$(function(){
	
	//-------Ê×Ò³ÅÅÁÐ
	if($('.divBox').length>0){
		$('.liBox1').each(function(i){
			$(this).attr('id','liBox1_'+i);
			})
		$('.liBox2').each(function(i){
			$(this).attr('id','liBox2_'+i);
			})
		$('.liBox3').each(function(i){
			$(this).attr('id','liBox3_'+i);
			})	
		indexFun();		
		}	
	$(window).resize(function(){
		indexFun()	
		})
	//---------
	if($('.liBox2').length>0){
		$('.liBox2').find('.contentBg').fadeTo(10,0);
		}
	$('.liBox2').hover(
	     function(){
			 $(this).find('.contentBg').fadeTo(500,1);
			 },
		 function(){
			 $(this).find('.contentBg').fadeTo(500,0);
			 }
	)
	//---------
	if($('.foot1').length>0){
		$('.foot1').find('.contentBg').fadeTo(10,0);
		}
	$('.foot1').find('li').hover(
	     function(){
			 $(this).find('.contentBg').fadeTo(500,1);
			 },
		 function(){
			 $(this).find('.contentBg').fadeTo(500,0);
			 }
	)
	
	if($('.indexBrand1').length>0){
		$('.indexBrand1').find('.contentBg').fadeTo(10,0);
		}
	$('.indexBrand1').hover(
	     function(){
			 $(this).find('.contentBg').fadeTo(500,1);
			 $(this).find('img').fadeTo(1000,0.8);
			 },
		 function(){
			 $(this).find('.contentBg').fadeTo(500,0);
			 $(this).find('img').fadeTo(1000,1);
			 }
	)
	if($('.indexBrand2').length>0){
		$('.indexBrand2').find('.contentBg').fadeTo(10,0);
		}
	$('.indexBrand2').hover(
	     function(){
			 $(this).find('.contentBg').fadeTo(500,1);
			 $(this).find('img').fadeTo(1000,0.8);
			 },
		 function(){
			 $(this).find('.contentBg').fadeTo(500,0);
			 $(this).find('img').fadeTo(1000,1);
			 }
	)
	
	if($('.liBox1').length>0){
	  $('.liBox1').find('.contentDiv').fadeTo('slow',0.8);
	  $('.liBox1').hover(
	     function(){
			 $(this).find('.img0').fadeTo(1000,0);
			 $(this).find('.contentDiv').fadeTo(1000,1);
			 },
		 function(){
			 $(this).find('.img0').fadeTo(1000,1);
			 $(this).find('.contentDiv').fadeTo(1000,0.8);
			 }
	  )	
	}
	//---
	if($('.case').length>0){
		$('.case').find('li').find('.bg').hide();
		$('.case').find('li').hover(
		  function(){
			  $(this).find('.bg').fadeTo(500,0.8);
			  $(this).find('.content').fadeTo(500,1);
			  },
		  function(){
			  $(this).find('.bg').fadeTo(500,0);
			  $(this).find('.content').fadeTo(500,0);
			  }
		)
		}
	//-------
	$('.lNav2').find('h2').each(function(i){
		$(this).click(function(){
			$('.lNav2').find('h2').removeClass('h2_now');
			$(this).addClass('h2_now');
			$('.lNav2').find('.list').slideUp("slow"); 
			$('.lNav2').find('.list').eq(i).slideDown("slow"); 
			})
		})	
	if($('.topA').length>0){
		$(window).scroll(function(){
			if($(window).scrollTop()>$(window).height()/2){
				$('.topA').fadeIn('slow');
				}else{
					$('.topA').fadeOut('slow');
					}
			})
		}
	if($('.topA3').length>0){
		$(window).scroll(function(){
			if($(window).scrollTop()>$(window).height()/2){
				$('.topA3').fadeIn('slow');
				}else{
					$('.topA3').fadeOut('slow');
					}
			})
		}	
	//----
	if($('.pageShow1').length>0){
		contactFun();
		}
	$(window).resize(function(){
		if($('.pageShow1').length>0){
		contactFun();
		}
		})			
	
	})
function contactFun(){
	var divWidth=$('.pageShow1').width();
		if(divWidth<=600){
			$('.pageShow1').css('padding-left',0);
			}else{
				$('.pageShow1').css('padding-left',200);
				}
	}	